# Generated by Django 5.2.14 on 2026-05-05 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnviroProRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, unique=True)),
                ('hum_s1_media', models.FloatField(blank=True, null=True)),
                ('hum_s2_media', models.FloatField(blank=True, null=True)),
                ('hum_s3_media', models.FloatField(blank=True, null=True)),
                ('hum_s4_media', models.FloatField(blank=True, null=True)),
                ('hum_s5_media', models.FloatField(blank=True, null=True)),
                ('hum_s6_media', models.FloatField(blank=True, null=True)),
                ('hum_s7_media', models.FloatField(blank=True, null=True)),
                ('hum_s8_media', models.FloatField(blank=True, null=True)),
                ('temp_s1_media', models.FloatField(blank=True, null=True)),
                ('temp_s1_max', models.FloatField(blank=True, null=True)),
                ('temp_s1_min', models.FloatField(blank=True, null=True)),
                ('temp_s2_media', models.FloatField(blank=True, null=True)),
                ('temp_s2_max', models.FloatField(blank=True, null=True)),
                ('temp_s2_min', models.FloatField(blank=True, null=True)),
                ('temp_s3_media', models.FloatField(blank=True, null=True)),
                ('temp_s3_max', models.FloatField(blank=True, null=True)),
                ('temp_s3_min', models.FloatField(blank=True, null=True)),
                ('temp_s4_media', models.FloatField(blank=True, null=True)),
                ('temp_s4_max', models.FloatField(blank=True, null=True)),
                ('temp_s4_min', models.FloatField(blank=True, null=True)),
                ('temp_s5_media', models.FloatField(blank=True, null=True)),
                ('temp_s5_max', models.FloatField(blank=True, null=True)),
                ('temp_s5_min', models.FloatField(blank=True, null=True)),
                ('temp_s6_media', models.FloatField(blank=True, null=True)),
                ('temp_s6_max', models.FloatField(blank=True, null=True)),
                ('temp_s6_min', models.FloatField(blank=True, null=True)),
                ('temp_s7_media', models.FloatField(blank=True, null=True)),
                ('temp_s7_max', models.FloatField(blank=True, null=True)),
                ('temp_s7_min', models.FloatField(blank=True, null=True)),
                ('temp_s8_media', models.FloatField(blank=True, null=True)),
                ('temp_s8_max', models.FloatField(blank=True, null=True)),
                ('temp_s8_min', models.FloatField(blank=True, null=True)),
                ('bateria_mv', models.IntegerField(blank=True, null=True)),
                ('panel_solar_mv', models.IntegerField(blank=True, null=True)),
                ('bateria_v', models.FloatField(blank=True, null=True)),
                ('panel_solar_v', models.FloatField(blank=True, null=True)),
                ('humedad_media', models.FloatField(blank=True, null=True)),
                ('humedad_minima', models.FloatField(blank=True, null=True)),
                ('humedad_maxima', models.FloatField(blank=True, null=True)),
                ('temperatura_media', models.FloatField(blank=True, null=True)),
                ('temperatura_minima', models.FloatField(blank=True, null=True)),
                ('temperatura_maxima', models.FloatField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('importado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'registro EnviroPro',
                'verbose_name_plural': 'registros EnviroPro',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
