# Generated by Django 5.2.14 on 2026-05-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(choices=[('sequedad_relativa', 'Sequedad relativa'), ('humedad_sensor_baja', 'Humedad baja en sensor'), ('temperatura_alta', 'Temperatura alta'), ('temperatura_incoherente', 'Temperatura incoherente'), ('bateria_baja', 'Bateria baja'), ('panel_solar_bajo', 'Panel solar bajo'), ('hueco_temporal', 'Hueco temporal')], db_index=True, max_length=40)),
                ('nivel', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Aviso'), ('critical', 'Critica')], db_index=True, max_length=20)),
                ('descripcion', models.TextField()),
                ('variable_afectada', models.CharField(max_length=80)),
                ('valor_detectado', models.FloatField(blank=True, null=True)),
                ('recomendacion_texto', models.TextField()),
                ('regla', models.CharField(max_length=120)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.enviroprorecord')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-fecha', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('record', 'tipo', 'regla'), name='unique_alert_by_record_type_rule')],
            },
        ),
    ]
