# Generated by Django 5.2.14 on 2026-05-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='tipo',
            field=models.CharField(choices=[('sequedad_relativa', 'Sequedad relativa'), ('humedad_sensor_baja', 'Humedad baja en sensor'), ('subida_brusca_humedad', 'Subida brusca de humedad'), ('caida_brusca_humedad', 'Caida brusca de humedad'), ('temperatura_alta', 'Temperatura alta'), ('temperatura_incoherente', 'Temperatura incoherente'), ('bateria_baja', 'Bateria baja'), ('panel_solar_bajo', 'Panel solar bajo'), ('sensor_bloqueado', 'Sensor posiblemente bloqueado'), ('hueco_temporal', 'Hueco temporal')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revision'), ('aplicada', 'Revisada'), ('descartada', 'Descartada')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
