# Generated by Django 5.2.14 on 2026-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_tipo_alter_recommendation_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='estado_manual',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('descartada', 'Descartada')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
